In [1]:
import numpy as np
import pandas as pd
import os
os.getcwd()
os.chdir('/Users/jackmcnally/Desktop/Stat 303-2/Final Project- Nashville Predators/team_data_by_szn')

In [15]:
szn_78 = pd.read_csv('teams_07_08.csv')
szn_89 = pd.read_csv('teams_08_09.csv')
szn_910 = pd.read_csv('teams_09_10.csv')
szn_1011 = pd.read_csv('teams_10_11.csv')
szn_1112 = pd.read_csv('teams_11_12.csv')
szn_1314 = pd.read_csv('teams_13_14.csv')
szn_1415 = pd.read_csv('teams_14_15.csv')
szn_1516 = pd.read_csv('teams_15_16.csv')
szn_1617 = pd.read_csv('teams_16_17.csv')
szn_1718 = pd.read_csv('teams_17_18.csv')

In [22]:
szn_lists = [szn_78, szn_89, szn_910, szn_1011, szn_1112, szn_1314, szn_1415, szn_1516, szn_1617, szn_1718]

In [24]:
full_szns = pd.concat(szn_lists, axis=0, ignore_index=True)

In [26]:
PO_teams = full_szns.loc[full_szns['made_playoffs']=="Yes"]

In [27]:
PO_teams

,Unnamed: 0,team_name,away_wins,home_wins,away_losses,home_losses,total_goals_scored,total_goals_against,made_playoffs
0,0,New Jersey Devils,21.0,25.0,20.0,16.0,206.0,197.0,Yes
1,1,Philadelphia Flyers,21.0,21.0,20.0,20.0,248.0,233.0,Yes
4,4,Boston Bruins,20.0,21.0,21.0,20.0,212.0,222.0,Yes
5,5,New York Rangers,17.0,25.0,24.0,16.0,213.0,199.0,Yes
6,6,Pittsburgh Penguins,21.0,26.0,20.0,15.0,247.0,216.0,Yes
...,...,...,...,...,...,...,...,...,...
317,20,Toronto Maple Leafs,20.0,29.0,21.0,12.0,277.0,232.0,Yes
321,24,Colorado Avalanche,15.0,28.0,26.0,13.0,257.0,237.0,Yes
323,26,Columbus Blue Jackets,19.0,26.0,22.0,15.0,242.0,230.0,Yes
324,27,Winnipeg Jets,20.0,32.0,21.0,9.0,277.0,218.0,Yes
326,29,Vegas Golden Knights,22.0,29.0,19.0,12.0,272.0,228.0,Yes

In [29]:
PO_teams.describe()

,Unnamed: 0,away_wins,home_wins,away_losses,home_losses,total_goals_scored,total_goals_against
count,160.000000,160.000000,160.00000,160.000000,160.00000,160.000000,160.000000
mean,11.456250,21.231250,25.08125,19.768750,15.91875,241.468750,215.018750
std,7.576733,2.724734,3.00936,2.724734,3.00936,20.624502,17.207016
min,0.000000,15.000000,18.00000,13.000000,9.00000,194.000000,165.000000
25%,5.750000,19.000000,23.00000,18.000000,14.00000,226.000000,202.000000
50%,10.500000,21.000000,25.00000,20.000000,16.00000,241.000000,216.000000
75%,16.000000,23.000000,27.00000,22.000000,18.00000,254.500000,229.000000
max,30.000000,28.000000,32.00000,26.000000,23.00000,318.000000,250.000000

In [30]:
import statsmodels.formula.api as smf
import seaborn as sns
import matplotlib.pyplot as plt

In [35]:
playoff_dummies = pd.get_dummies(full_szns['made_playoffs'])
playoff_dummies['Yes']

0      1
1      1
2      0
3      0
4      1
      ..
325    0
326    1
327    0
328    0
329    0
Name: Yes, Length: 330, dtype: uint8

In [38]:
playoff_dummies = pd.get_dummies(full_szns, prefix = ['made_playoffs'], columns = ['made_playoffs'])
playoff_dummies

,Unnamed: 0,team_name,away_wins,home_wins,away_losses,home_losses,total_goals_scored,total_goals_against,made_playoffs_No,made_playoffs_Yes
0,0,New Jersey Devils,21.0,25.0,20.0,16.0,206.0,197.0,0,1
1,1,Philadelphia Flyers,21.0,21.0,20.0,20.0,248.0,233.0,0,1
2,2,Los Angeles Kings,15.0,17.0,26.0,24.0,231.0,266.0,1,0
3,3,Tampa Bay Lightning,11.0,20.0,30.0,21.0,223.0,267.0,1,0
4,4,Boston Bruins,20.0,21.0,21.0,20.0,212.0,222.0,0,1
...,...,...,...,...,...,...,...,...,...,...
325,28,Edmonton Oilers,17.0,19.0,24.0,22.0,234.0,263.0,1,0
326,29,Vegas Golden Knights,22.0,29.0,19.0,12.0,272.0,228.0,0,1
327,30,Carolina Hurricanes,17.0,19.0,24.0,22.0,228.0,256.0,1,0
328,31,Arizona Coyotes,13.0,16.0,28.0,25.0,208.0,256.0,1,0
329,32,Atlanta Thrashers,0.0,0.0,0.0,0.0,0.0,0.0,1,0

In [39]:
model = smf.ols(formula = 'made_playoffs_Yes~away_wins+home_wins+away_losses+home_losses+total_goals_scored+total_goals_against', data = playoff_dummies).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      made_playoffs_Yes   R-squared:                       0.670
Model:                            OLS   Adj. R-squared:                  0.665
Method:                 Least Squares   F-statistic:                     131.6
Date:                Wed, 22 Feb 2023   Prob (F-statistic):           8.13e-76
Time:                        16:48:04   Log-Likelihood:                -56.369
No. Observations:                 330   AIC:                             124.7
Df Residuals:                     324   BIC:                             147.5
Df Model:                           5
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept           -3.301e-15      0.054  -6.14e-14      1.000      -0.106       0.106
away_wins               0.0356      0.005      6.752      0.000       0.025       0.046
home_wins               0.0349      0.005      6.702      0.000       0.025       0.045
away_losses            -0.0086      0.005     -1.655      0.099      -0.019       0.002
home_losses            -0.0079      0.005     -1.523      0.129      -0.018       0.002
total_goals_scored      0.0012      0.002      0.762      0.447      -0.002       0.004
total_goals_against    -0.0037      0.002     -2.400      0.017      -0.007      -0.001
==============================================================================
Omnibus:                       12.733   Durbin-Watson:                   2.148
Prob(Omnibus):                  0.002   Jarque-Bera (JB):                7.143
Skew:                          -0.173   Prob(JB):                       0.0281
Kurtosis:                       2.368   Cond. No.                     3.80e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.25e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""